name: course_app

networks:
    course_net:
      driver: bridge

volumes:
    course_data:

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      target: production
    environment:
      YII_ENV: "prod"
      YII_DEBUG: "false"
      # Beispiel f√ºr API-Basis-URL Richtung Backend:
      # API_BASE_URL: "http://localhost:8081"
    ports:
      - "8080:80"
    networks:
      - course_net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "5689"
      DEBUG: "false"
      LOGLEVEL: "INFO"
    ports:
      - "8081:${PORT:-5689}"
    networks:
      - course_net

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    ports:
    - "1521:1521"
    - "5500:5500"
    volumes:
    - course_data:/opt/oracle/oradata:Z
    environment:
    - ORACLE_PWD=password
    networks:
    - course_net

  db-migration:
    image: ghcr.io/oracle/oraclelinux9-instantclient:23
    depends_on:
      - oracle-db
    volumes:
      - ./DB/init/db_init.sh:/scripts/db_init.sh:ro
      - ./DB/init/sql/01_Migration.sql:/scripts/migration.sql:ro
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=app
      - APP_PASSWORD=apppassword
      - ORACLE_HOST=oracle-db
      - ORACLE_PORT=1521
      - ORACLE_SERVICE=FREEPDB1
    networks:
      - course_net
    command: ["sh", "/scripts/db_init.sh"]
    restart: "no"
